### ISSUE TITLE
Recommendation for adding "forgot password"?

### ISSUE THREAD

**Issue by andyhullinger** [drhurdle/node-rethinkdb-auth-starter#3]
Nice jump start to a project for me, but I need to add a "forgot" password reset. Any recommendation for how to implement this or which middleware/methods to investigate?

**Comment by drhurdle** [comment]
Sorry this took so long to address.  Things have just gotten really busy.  I have not researched a whole lot when it comes to the best way to resetting passwords.  This wasn't something I wanted to try to implement in this start project because different methods may be appropriate depending on the type of application you are writing.  I am going to close this for now but if I find something that seems to really fit this project, I will reopen this and resolve it with the new code
